name: CI-CD
on: 
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    # - name: lint
    #   run: npm run lint
    
    # - name: Unit tests
    #   run: npm run test
    
  build: 
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    # - name: Build app
    #   run: npm run build --prod
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: devops-test-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/devops-test

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps: 
    # - name: Dowload artifact
    #   uses: actions/download-artifact@v2
    #   with: 
    #     name: devops-test-${{ github.run_id }}-${{ github.run_number }} 
    #     path: './build'

    - name: Deploy App
      uses: actions/checkout@v2
    
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.LA_BELLE_PLANTE_BACK }}
        heroku_app_name: "labelleplanteback"
        heroku_email: "gaellecoue@gmail.com"
